buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
    }
}
apply plugin: 'com.android.application'

android {
    namespace 'com.example.remotecontrol'
    compileSdk 34
    defaultConfig {
        applicationId "com.example.remotecontrol"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "02.28-FULL"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.android.material:material:1.10.0'
    implementation 'com.google.android.gms:play-services-location:21.0.1'
    implementation 'androidx.core:core:1.12.0'
}
